version: '3'

services:
  app:
    container_name: car-dealership-app
    build:
      context: .
      dockerfile: Dockerfile
      restart: unless stopped
    volumes:
      - './car-dealership-app:/usr/src/app'
      - 'usr/src/app/node_modules'
    ports:
      - '8081:8081'